DROP TABLE IF EXISTS BASE_STATION;
CREATE TABLE BASE_STATION (
	  ID INT NOT NULL AUTO_INCREMENT
	, BS_TITLE VARCHAR(10) NOT NULL
	, DESCRIPTION VARCHAR(255)
	, CREATE_DATE DATE
	, APPLICATION BLOB
	, VERSION INT NOT NULL DEFAULT 0
	, UNIQUE UQ_BS_1 (BS_TITLE)
	, PRIMARY KEY (ID)
);

